# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 9mY8uk9RAqMbTG5L
    ports:
      - 7432:5432

